name: Run tests
on: push
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.4', '8.0', '8.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          tools: composer
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ matrix.version }}-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit
